### ISSUE TITLE
Timeout error message

### ISSUE THREAD

**Issue by bdunbar22** [camsong/fetch-jsonp#11]
Hello,

The given URL is updated to include a '?' or '&' which is added so that the callback can be appended correctly. Upon errors, the `reject(new Error(`JSONP request to ${url} timed out`)); ` will include the character that was added. This isn't a big deal but at first made me think a URL might be wrong because of the additional character. I think a quick fix to return an unmodified original URL during error messages would be beneficial.

**Comment by camsong** [comment]
released https://github.com/camsong/fetch-jsonp/tree/v1.0.2
