### ISSUE TITLE
IE9 support

### ISSUE THREAD

**Issue by stephenmangion** [camsong/fetch-jsonp#15]
HI, I am trying to get the fetch-jsonp to work on IE9 without any success. Is there a way you can provide a working example please? I think promises are not supported by IE9 whihc makes this modules not work in IE9. can you provide a simple example please?

**Comment by camsong** [comment]
Did you use `es6-promise`?
`https://github.com/camsong/fetch-jsonp#promise-polyfill-for-ie`

**Comment by stephenmangion** [comment]
Can you provide an example please? I couldnt get it to work...

**Comment by camsong** [comment]
I added a example [index-ie8.html](https://github.com/camsong/fetch-jsonp/blob/master/examples/index-ie8.html#L6).

You can run this link in browser https://cdn.rawgit.com/camsong/fetch-jsonp/master/examples/index-ie8.html

**Comment by stephenmangion** [comment]
Thanks mate. that worked like a charm
