### ISSUE TITLE
Could not find a declaration file for module 'fetch-jsonp'

### ISSUE THREAD

**Issue by jerexyz** [camsong/fetch-jsonp#17]
[ts] Could not find a declaration file for module 'fetch-jsonp'. '/Users/jere/jm/jumei-sdk/node_modules/fetch-jsonp/build/fetch-jsonp.js' implicitly has an 'any' type.

**Comment by jerexyz** [comment]
很好的一个库，什么时候可以支持typescript呢？

**Comment by camsong** [comment]
I'm not familiar with typescript, can you make a PR?

**Comment by jerexyz** [comment]
a pr for this: https://github.com/camsong/fetch-jsonp/pull/18
