### ISSUE TITLE
fetchJsonp should return Promise

### ISSUE THREAD

**Issue by doxiaodong** [camsong/fetch-jsonp#19]
https://github.com/camsong/fetch-jsonp/blob/master/index.d.ts#L7

It should return Promise not Function

**Comment by camsong** [comment]
@doxiaodong can you help to make a PR?
I'm not familiar with TypeScript syntax. thanks

**Comment by doxiaodong** [comment]
@camsong ，ok.

**Comment by camsong** [comment]
Released v1.0.5
