### ISSUE TITLE
typescript declare error

### ISSUE THREAD

**Issue by jerexyz** [camsong/fetch-jsonp#23]
`ERROR in /Users/jere/jm/jumei-sdk/node_modules/fetch-jsonp/index.d.ts
(1,73): error TS2304: Cannot find name 'Promise'.`

**Comment by camsong** [comment]
`Promise` in a feature of ES6, it seems that you can install globally to fix this.

```js
typings install --global es6-promise
```

http://stackoverflow.com/a/37924017

**Comment by jerexyz** [comment]
👍
