### ISSUE TITLE
Request blocked due to MIME type mismatch (X-Content-Type-Options: nosniff)

### ISSUE THREAD

**Issue by LouWii** [camsong/fetch-jsonp#27]
Hi there,

I'm using fetch-jsonp to fecth some JSON, but Firefox is blocking my request and throw this message in the console.

The resource from “http://xxxxxxxxxxxxxxx&custom_callback=jsonp_1488599283507_98115” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).

Is there any work-around ? Or am I screwed ?

Thanks

**Comment by vd007** [comment]
Hi,
Have you got the solution for this?

**Comment by jpaulino04** [comment]
Are you using express?

Check your path(note the "/" after /public/): 
app.use(express.static(__dirname + "/public/"));


//note: you do not need the "/" before "css" because its already included above.
<link rel="stylesheet" href="css/style.css">

Hope this helps

**Comment by LouWii** [comment]
I'm not using Express, this was for a React app.
I never found any solution for this, I ended up not using this lib, and added some cross domain attributes in requests Header my Apache configuration to fix the CORS problem.

**Comment by camsong** [comment]
According to MDN, there are may be two reasons for this:

> nosniff
>   Blocks a request if the requested type is
>      "style" and the MIME type is not "text/css", or
>      "script" and the MIME type is not a JavaScript MIME type.
so check the server's response header of MIME type
