### ISSUE TITLE
Using headers not possible?

### ISSUE THREAD

**Issue by TonySpegel** [camsong/fetch-jsonp#28]
Hi there, thanks for this awesome library.

I'm having trouble using your library while adding a header.
First what I usually do using jQuery:
`$.ajax({
    url     : 'https://api.imgur.com/3/gallery/t/cats/45',  
    type    : 'GET',
    dataType: 'json',
    headers: {
        Authorization: 'Client-ID ' + IMGUR_API_CLIENT_ID
    },
    success: function(json) {
        for (let item of json.data.items) {
            console.log(item);
        }
});`

and now using fetchJsonp:
`let galleryURL = 'https://api.imgur.com/3/gallery/t/cats/45';

fetchJsonp(galleryURL, {
    url: galleryURL,
    method: 'get',
    dataType: 'json',
    headers: {
        Authorization: 'Client-ID ' + IMGUR_API_CLIENT_ID
    }
}).then(function(response) {
    return response.json();
}).then(function(json) {
    console.log(json);
});`

Can you help me, am I doing something wrong? Are headers supported by fetch-jsonp?
Thanks a lot

Edit: I'm using this combined with aurelia,js and I'm getting a 
"Unhandled rejection Error: JSONP request to https://api.imgur.com/3/gallery/t/cats/45 timed out"-Error

**Comment by camsong** [comment]
JSONP use `script` to simulate ajax request, so header is not supported. You can ask to the server if it support using request parameter to replace header.
