### ISSUE TITLE
Uncaught SyntaxError: Unexpected token :

### ISSUE THREAD

**Issue by marineb** [camsong/fetch-jsonp#32]
I'm probably doing something wrong. 

I have this: 

```
    fetchJsonp(url, {
        timeout: 3000,
        jsonpCallback: 'custom_callback'
      })
      .then(function(response) {
        return response.json()
      }).then(function(json) {
        console.log('parsed json', json)
      }).catch(function(ex) {
        console.log('parsing failed', ex)
      });
```

But I'm getting this error: 
`Uncaught SyntaxError: Unexpected token :` on my fetched URL. 

Thank you!

**Comment by ZMil** [comment]
Having the same issue, did you ever figure out a solution?

**Comment by camsong** [comment]
What's the request response?

**Comment by fengyun2** [comment]
me too!

**Comment by camsong** [comment]
@fengyun2 can you add a test page to reproduce the error?

**Comment by ZMil** [comment]
@camsong the response is the error` SyntaxError: Unexpected token ':'. Parse error.` which is then followed by a timeout error.

To give a little background, I've tried using axios, super agent, and fetch to retrieve data from google maps directions. For each one, I receive the error along the lines of `XMLHttpRequest cannot load (api endpoint) Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin.` 

I've been able to get around this during development by disabling some chrome security features, but read jsonp might be able to solve this problem for me.

**Comment by camsong** [comment]
@ZMil which version are you using?

**Comment by ZMil** [comment]
@camsong fetch-jsonp@1.1.1

**Comment by michaelghinrichs** [comment]
Also having this issue!
```
fetch-jsonp@^1.1.1:
  version "1.1.1"
  resolved "https://registry.yarnpkg.com/fetch-jsonp/-/fetch-jsonp-1.1.1.tgz#b7b9fd7d3a4f74d38389f5ea2f2d0f46c34510e4"
```

**Comment by camsong** [comment]
Can anyone submit a [jsfiddle](http://jsfiddle.net/) to reproduce the error? I'd like to fix this asap if I got how to reproduce 😸

**Comment by camsong** [comment]
@marineb Finally I can reproduce your error. It's because your are calling a JSON api, which does not support JSONP. The difference is that JSON api respond with an object like `{"data": 123}`, will got above error when being executed as function. While JSONP will respond with a function wrapped object like `jsonp_123132({data: 123})`.

**Comment by marineb** [comment]
Yes thank you! I ended up resolving it but forgot to return to this issue.
