### ISSUE TITLE
Getting error as MIME type ('application/json') is not executable

### ISSUE THREAD

**Issue by athimannil** [camsong/fetch-jsonp#37]
I am getting error as this in console. 

``Refused to execute script from 'https://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en&callback=jsonp_1500375938057_49602' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.``

<img width="557" alt="screen shot 2017-07-18 at 1 07 05 pm" src="https://user-images.githubusercontent.com/4364227/28314277-2d3f6ab0-6bba-11e7-95fa-b54666c99959.png">

Could you please let me know a solution ?

**Comment by camsong** [comment]
It seems the backend does not support JSONP, the response should be a javascript function not a JSON as described. Please refer to your backend dev for help

**Comment by athimannil** [comment]
The issue has been solved in JSONP

```
fetchJsonp(urlForQuote, {
	jsonpCallback: "callback",
	jsonpCallbackFunction: "callback"
        })
	.then(function(response) {
		return response.json();
	})
	.then(
		function(json) {
			this.setState({
				text: json.quoteText,
				author: json.quoteAuthor,
			});
		}.bind(this)
	)
	.catch(function(ex) {
		console.log("API call failed", ex);
	});
```
