### ISSUE TITLE
parsing failed Error: JSONP request to 'xxx ' timed out     at fetch-jsonp.js:85

### ISSUE THREAD

**Issue by heyunjiang** [camsong/fetch-jsonp#38]
```
fetchJsonp(url, {
      jsonpCallback: 'jsoncallback',
      timeout: 3000
    })
	  .then(function(response) {
	  	console.log(response)
	    return response.json()
	  }).then(function(json) {
	    console.log('parsed json', json)
	  }).catch(function(ex) {
	    console.log('parsing failed', ex)
	  })
```
数据也能返回
![image](https://user-images.githubusercontent.com/15085454/29159403-fceef82e-7de0-11e7-93c9-c83cef1d038f.png)
浏览器控制台
![image](https://user-images.githubusercontent.com/15085454/29159442-26a55334-7de1-11e7-87de-46a3a21611da.png)

请问下我该怎么解决这个问题，还是我没有写正确

**Comment by nejohnston** [comment]
Also receiving this error!

**Comment by camsong** [comment]
这是个 JSON 接口，而不是 JSONP 接口。JSONP 返回的是带回调的 JS 函数
