### ISSUE TITLE
How to mock using nock or any other?

### ISSUE THREAD

**Issue by sanjitbauli** [camsong/fetch-jsonp#42]
ReferenceError: window is not defined

**Comment by camsong** [comment]
Nock doesn't support jsonp right now https://github.com/node-nock/nock/issues/761 , you can use https://github.com/tmpvar/jsdom to get ride of `window` undefined error in node environment

**Comment by bartvde** [comment]
does anyone have an example on how to mock this? TIA

**Comment by bartvde** [comment]
ah I got it to work with something like this combined with nock in jest:

```
// __mocks__/fetch-jsonp.js
'use strict';

const fetchjsonp = jest.genMockFromModule('fetch-jsonp');

module.exports = function(url) {
  return fetch(url);
};
```
