### ISSUE TITLE
CORS FETCH on IE9

### ISSUE THREAD

**Issue by CoderNie** [camsong/fetch-jsonp#46]
I use fetch-ie8 on an app based on react, and I apply CORS FETCH on this app, the fetch request always fails on IE9 ( the problem is 拒绝访问 Access denied ) , if I wanna insist on CORS FETCH, does it mean I have to use fetch-jsonp? Is there any better way?
p.s.
I've read your blog on https://github.com/camsong/blog/issues/2 , great job!

**Comment by camsong** [comment]
Using fetch-ie8 is the right way to go, no need to used fetch-jsonp.
Can you make a demo to reproduce the error, I tested [my demo](https://github.com/camsong/fetch-ie8/blob/master/examples/index.html) on ie9 and it works.
