### ISSUE TITLE
404 Why 'catch' can't catch?

### ISSUE THREAD

**Issue by river-lee** [camsong/fetch-jsonp#5]
404 Why 'catch' can't catch?

**Comment by camsong** [comment]
Right now it use a `timeout`(default to 5 seconds) to catch error. JSONP uses a `<script>` to make request, when the `<script>` failed, the plugin is not informed, that's why I used `setTimeout`

**Comment by river-lee** [comment]
Why use time out, rather than judge onload <script/>

**Comment by camsong** [comment]
Not sure if script onload supports IE8+?

**Comment by river-lee** [comment]
If supported, the onload is more appropriate?
And then use a timeout?

**Comment by camsong** [comment]
yep, this would be great. Can you help to investigate this?

**Comment by river-lee** [comment]
IE8 does not support the "onerror"; but you can determine whether to download through the onreadyState, and then through the characteristics of the callback, check the overall function jsonp, to verify the results.
