### ISSUE TITLE
add support for abort signal???

### ISSUE THREAD

**Issue by hoogw** [camsong/fetch-jsonp#55]
I want to use abort function, like standard Fetch 
see signal api at
[https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch)

abortController = new AbortController()
signal = abortController.signal

fetch( url, {signal})

I want to use same as fetchjsonp( url, {signal})

How to do that?

**Comment by camsong** [comment]
abort make sense, but can not fine a easy way to implement recently.
