### ISSUE TITLE
Library does not support nonce

### ISSUE THREAD

**Issue by tylerl-ms** [camsong/fetch-jsonp#56]
Hi.  Library has worked great so far, but does not respect a nonce value so our Urls cannot be added to the page.  i.e. when the nonce value is set, every script added to the page must use the known nonce value.

Ideally we need this added:
      if (options.nonce) {
        jsonpScript.setAttribute('nonce', options.nonce);
      }

Thanks!
Tyler

**Comment by camsong** [comment]
Supported in https://github.com/camsong/fetch-jsonp/releases/tag/v1.2.0
