### ISSUE TITLE
Call the local interface in react to report timed out

### ISSUE THREAD

**Issue by xiaoniu945** [camsong/fetch-jsonp#59]
It’s a demo written by myself. As a result, this problem occurs after using fetch-jsonp to cross domains, but the data is returned normally, the console will report this error
Uncaught (in promise) Error: JSONP request to http://localhost:8081/movie/in_theaters?start=0&count=14 timed out
    at eval (fetch-jsonp.js:80)

**Comment by Kehao33** [comment]
parsing failed Error: JSONP request to https://www.xxxx.com/blog/ timed out, I also have the question,need help too.

**Comment by camsong** [comment]
Your server needs to support jsonp, may refer to https://github.com/typicode/json-server
